#!/bin/bash
set -eu

source /usr/share/yunohost/helpers
source "$(dirname "$0")/_common.sh"

ynh_script_progression "Setting up source files..."
ynh_setup_source --dest_dir="$install_dir"

ynh_script_progression "Building Mangatsu..."
build_mangatsu

ynh_script_progression "Configuring NGINX..."
ynh_config_add_nginx

ynh_script_progression "Installation of $app completed"
