#!/bin/bash
set -eu

source /usr/share/yunohost/helpers

ynh_script_progression "Removing NGINX configuration..."
ynh_config_remove_nginx

ynh_script_progression "Removing Mangatsu files..."
ynh_safe_rm "$install_dir"

ynh_script_progression "Removal of $app completed"
