#!/bin/bash
set -eu

source /usr/share/yunohost/helpers
source "$(dirname "$0")/_common.sh"

ynh_script_progression "Refreshing source files..."
ynh_setup_source --dest_dir="$install_dir"

ynh_script_progression "Rebuilding Mangatsu..."
build_mangatsu

ynh_script_progression "Updating NGINX configuration..."
ynh_config_add_nginx

ynh_script_progression "Upgrade of $app completed"
